### ISSUE TITLE
Is social-auth-storage-sqlalchemy dependency needed?

### ISSUE THREAD

**Issue by stefanv** [python-social-auth/social-app-tornado#1]
The social-auth-app-tornado package pulls in SQLAlchemy.  Is this strictly necessary?

We use Peewee in our project, and would prefer not to bloat the dependency list unnecessarily.

**Comment by omab** [comment]
Currently the app depends on `SQLAlchemy` (check the [models.py](https://github.com/python-social-auth/social-app-tornado/blob/4fa462382ac4b3bd23a6db4e0b71e4760cb7bc36/social_tornado/models.py#L32-L62) definition).

The same approach followed by [social-app-flask](https://github.com/omab/social-app-flask) could be implemented in this app to decouple the storage backend.

**Comment by stefanv** [comment]
I have a fully working PSA + Tornado + Peewee put together.  Would it be useful to refactor it into an example?

The two main parts are:

https://github.com/cesium-ml/cesium_web/pull/175/files#diff-9950db85dd624c5624b622a6a7297441R1

and

https://github.com/cesium-ml/cesium_web/pull/175/files#diff-af1d146e60736dfd76b5dadb50abeaefR40

I also have an example "Fake" Google OAuth2 server that I use for testing.  I wonder how other people test their authentication systems locally; oddly I don't see much talk of that.

**Comment by stefanv** [comment]
For anyone looking into OAuth2 testing, here's the link to our code: https://github.com/cesium-ml/baselayer/blob/master/services/fake_oauth2.py

We're no longer using PeeWee, so I'll close this issue for now.
